// Auto-generated. Do not edit directly.
export default {
  "Welcome to Multiplication Tables!": "/assets/audio/audio_welcome_to_multiplication_tables__9h3hd.mp3",
  "Today we will master the times tables for six, seven, eight, and nine.": "/assets/audio/audio_today_we_will_master_the_times_tables_fo_boj77.mp3",
  "Can you spot patterns and solve multiplication facts quickly?": "/assets/audio/audio_can_you_spot_patterns_and_solve_multipli_42cxj.mp3",
  "Are you ready to explore four amazing worlds and become a multiplication master? Let us begin!": "/assets/audio/audio_are_you_ready_to_explore_four_amazing_wo_ofdds.mp3",
  "Sarah explores the coral reef and discovers rows of six colourful fish.": "/assets/audio/audio_sarah_explores_the_coral_reef_and_discov_4j1dm.mp3",
  "How many fish are there when there are four rows of six?": "/assets/audio/audio_how_many_fish_are_there_when_there_are_f_j9p5l.mp3",
  "That is what the six times table helps us find out!": "/assets/audio/audio_that_is_what_the_six_times_table_helps_u_4hzxj.mp3",
  "Miguel swings through the jungle canopy counting groups of seven.": "/assets/audio/audio_miguel_swings_through_the_jungle_canopy__hckjx.mp3",
  "Seven is tricky, but patterns and practice make it easier!": "/assets/audio/audio_seven_is_tricky__but_patterns_and_practi_cauh5.mp3",
  "John floats in the space station. Each fuel pod holds eight litres.": "/assets/audio/audio_john_floats_in_the_space_station__each_f_6xojl.mp3",
  "Eight is double-double — a handy trick for the eights!": "/assets/audio/audio_eight_is_double_double___a_handy_trick_f_scbfd.mp3",
  "Aiko unlocks the ancient temple and learns the nine times table.": "/assets/audio/audio_aiko_unlocks_the_ancient_temple_and_lear_1beqa.mp3",
  "The digits of nine times facts always add up to nine!": "/assets/audio/audio_the_digits_of_nine_times_facts_always_ad_g4nip.mp3",
  "You have met all four table worlds!": "/assets/audio/audio_you_have_met_all_four_table_worlds__biwzq.mp3",
  "Now it is time to practice building arrays and solving challenges!": "/assets/audio/audio_now_it_is_time_to_practice_building_arra_i90ka.mp3",
  "Tap each circle to build equal rows for multiplication!": "/assets/audio/audio_tap_each_circle_to_build_equal_rows_for__afqty.mp3",
  "Put the same number in every group. Can you fill them all?": "/assets/audio/audio_put_the_same_number_in_every_group__can__3gmrc.mp3",
  "Look at these multiplication arrays. Which one matches the sentence?": "/assets/audio/audio_look_at_these_multiplication_arrays__whi_epf7p.mp3",
  "Tap the correct arrangement!": "/assets/audio/audio_tap_the_correct_arrangement__8hnv2.mp3",
  "Fill in the missing number. Use the number pad!": "/assets/audio/audio_fill_in_the_missing_number__use_the_numb_ic8lu.mp3",
  "Welcome to Coral Reef!": "/assets/audio/audio_welcome_to_coral_reef__y367u.mp3",
  "Welcome to Jungle Canopy!": "/assets/audio/audio_welcome_to_jungle_canopy__3qurs.mp3",
  "Welcome to Space Station!": "/assets/audio/audio_welcome_to_space_station__cactj.mp3",
  "Welcome to Ancient Temple!": "/assets/audio/audio_welcome_to_ancient_temple__6g9we.mp3",
  "Coral Reef Complete!": "/assets/audio/audio_coral_reef_complete__fnbj8.mp3",
  "Jungle Canopy Complete!": "/assets/audio/audio_jungle_canopy_complete__kvjzx.mp3",
  "Space Station Complete!": "/assets/audio/audio_space_station_complete__muug8.mp3",
  "Ancient Temple Complete!": "/assets/audio/audio_ancient_temple_complete__5b4jl.mp3",
  "What did you learn about multiplication tables?": "/assets/audio/audio_what_did_you_learn_about_multiplication__u2g8p.mp3",
  "How confident do you feel about times tables six through nine?": "/assets/audio/audio_how_confident_do_you_feel_about_times_ta_0t6d8.mp3"
};
